### ISSUE TITLE
Brand assets

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/.github#5]
![primitive-wordmark-on-dark](https://user-images.githubusercontent.com/38409137/214508202-218ec073-fee6-47c7-acb7-075e02991637.png)

**Comment by Alexangelj** [comment]
![primitive-wordmark-on-light](https://user-images.githubusercontent.com/38409137/214508378-0c496fdd-4ce4-4423-a059-8b0d28d563f9.png)

**Comment by 0xJepsen** [comment]
Closed with recent PR
